// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jovnxhdhymsbhdzgqucr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvdm54aGRoeW1zYmhkemdxdWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzQ5NjAsImV4cCI6MjA3MzcxMDk2MH0.IxaJhoeq45T9959Tglo98GQtwQbd6Zep7CaFVBCu0lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});